# This is a basic workflow to help you get started with Actions

# Name of the workflow
name: Build HA Addon

# Triggers the workflow on manual dispatch
on: workflow_dispatch

# Defines the steps that will run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} open3e add-on
    strategy:
      matrix:
        addon: ["open3e"]
        arch: ["aarch64", "amd64", "armhf"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Open3e add-on
        if: contains(steps.info.outputs.architectures, matrix.arch)
        uses: home-assistant/builder@2025.02.0
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --image "ha-addon-open3e-${{ matrix.arch }}" \
            --docker-hub fleckem
